# Generated by Django 6.0.2 on 2026-03-06 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloSimilaridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Similitud del coseno entre 0 y 1')),
                ('titulo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similitudes_hacia', to='universidad.titulo')),
                ('titulo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similitudes_desde', to='universidad.titulo')),
            ],
            options={
                'verbose_name': 'Similitud entre títulos',
                'verbose_name_plural': 'Similitudes entre títulos',
                'constraints': [models.UniqueConstraint(fields=('titulo_origen', 'titulo_destino'), name='unique_titulo_similaridad_par')],
            },
        ),
    ]
