# Generated by Django 6.0.2 on 2026-03-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0002_add_titulo_similaridad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Related',
        ),
    ]
