# Generated by Django 6.0.2 on 2026-03-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0003_remove_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='universidad',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_universidades/'),
        ),
    ]
