# Generated by Django 6.0.2 on 2026-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0004_universidad_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='empleabilidad',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Porcentaje estimado de empleabilidad (0-100).', null=True),
        ),
    ]
