# Generated by Django 6.0.2 on 2026-03-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0005_area_empleabilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='empleabilidad',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Porcentaje estimado de empleabilidad (0-100, admite 1 decimal).', max_digits=4, null=True),
        ),
    ]
